const HABITS_KEY="habitTracker.habits.v1",LOG_KEY="habitTracker.log.v1",SETTINGS_KEY="habitTracker.settings.v1";
function uid(){return"h_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,9)}
function todayISO(){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),dd=String(d.getDate()).padStart(2,"0");return`${y}-${m}-${dd}`}
function parseISO(i){const[a,b,c]=i.split("-").map(Number);return new Date(a,b-1,c,12,0,0,0)}
function isoFromDate(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),dd=String(d.getDate()).padStart(2,"0");return`${y}-${m}-${dd}`}
function dowIndex(d=new Date()){return d.getDay()}
function escapeHtml(s){const d=document.createElement("div");d.textContent=String(s??"");return d.innerHTML}
function loadJSON(k,f){try{const r=localStorage.getItem(k);return r?JSON.parse(r):f}catch{return f}}
function saveJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}
function defaultHabits(){return[{id:uid(),name:"Вода",emoji:"💧",type:"count",goal:8,days:[1,2,3,4,5,6,0]},{id:uid(),name:"Прогулка",emoji:"🚶‍♀️",type:"check",goal:1,days:[1,2,3,4,5,6,0]}]}
let state={tab:"today",habits:loadJSON(HABITS_KEY,null),log:loadJSON(LOG_KEY,{}),settings:loadJSON(SETTINGS_KEY,{pinHash:null})};
if(!Array.isArray(state.habits)){state.habits=defaultHabits();saveJSON(HABITS_KEY,state.habits)}
const viewEl=document.getElementById("view"),subtitleEl=document.getElementById("subtitle"),tabs=[...document.querySelectorAll(".tab")];
const habitModal=document.getElementById("habitModal"),habitModalTitle=document.getElementById("habitModalTitle"),habitCloseBtn=document.getElementById("habitCloseBtn"),habitCancelBtn=document.getElementById("habitCancelBtn"),habitDeleteBtn=document.getElementById("habitDeleteBtn"),habitForm=document.getElementById("habitForm"),habitEditingId=document.getElementById("habitEditingId"),habitName=document.getElementById("habitName"),habitEmoji=document.getElementById("habitEmoji"),habitType=document.getElementById("habitType"),goalField=document.getElementById("goalField"),habitGoal=document.getElementById("habitGoal"),dowChks=[...document.querySelectorAll(".dowChk")];
document.getElementById("addHabitBtn").addEventListener("click",()=>openHabitModal(null));
const settingsBtn=document.getElementById("settingsBtn"),settingsModal=document.getElementById("settingsModal"),settingsCloseBtn=document.getElementById("settingsCloseBtn"),settingsDoneBtn=document.getElementById("settingsDoneBtn"),pinActionBtn=document.getElementById("pinActionBtn"),exportBtn=document.getElementById("exportBtn"),importFile=document.getElementById("importFile");
const lockEl=document.getElementById("lock"),pinInput=document.getElementById("pinInput"),pinUnlockBtn=document.getElementById("pinUnlockBtn"),pinError=document.getElementById("pinError");
const pinModal=document.getElementById("pinModal"),pinModalTitle=document.getElementById("pinModalTitle"),pinCloseBtn=document.getElementById("pinCloseBtn"),pinCancelBtn=document.getElementById("pinCancelBtn"),pinDisableBtn=document.getElementById("pinDisableBtn"),pinForm=document.getElementById("pinForm"),pinHasExisting=document.getElementById("pinHasExisting"),pinOld=document.getElementById("pinOld"),pinNew=document.getElementById("pinNew"),pinNew2=document.getElementById("pinNew2");
function registerSW(){if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(console.error)}
function isHabitActiveToday(h){const d=dowIndex(new Date());return Array.isArray(h.days)&&h.days.includes(d)}
function getLogValue(dateISO,id){return state.log?.[dateISO]?.[id]}
function setLogValue(dateISO,id,val){state.log[dateISO]=state.log[dateISO]||{};state.log[dateISO][id]=val;saveJSON(LOG_KEY,state.log)}
function normalizeHabit(h){return{id:h.id??uid(),name:String(h.name??"Привычка"),emoji:String(h.emoji??""),type:h.type==="count"?"count":"check",goal:Math.max(1,Number(h.goal??1)||1),days:Array.isArray(h.days)?h.days:[1,2,3,4,5,6,0]}}
function syncGoalField(){habitType.value==="count"?goalField.classList.remove("hidden"):goalField.classList.add("hidden")}
habitType.addEventListener("change",syncGoalField);
function openHabitModal(edit){habitModal.classList.remove("hidden");if(edit){habitModalTitle.textContent="Редактировать привычку";habitEditingId.value=edit.id;habitName.value=edit.name;habitEmoji.value=edit.emoji||"";habitType.value=edit.type;habitGoal.value=edit.goal||1;dowChks.forEach(ch=>ch.checked=edit.days.includes(Number(ch.value)));habitDeleteBtn.classList.remove("hidden")}else{habitModalTitle.textContent="Добавить привычку";habitEditingId.value="";habitName.value="";habitEmoji.value="";habitType.value="check";habitGoal.value=8;dowChks.forEach(ch=>ch.checked=!0);habitDeleteBtn.classList.add("hidden")}syncGoalField()}
function closeHabitModal(){habitModal.classList.add("hidden")}
habitCloseBtn.addEventListener("click",closeHabitModal);
habitCancelBtn.addEventListener("click",closeHabitModal);
habitModal.addEventListener("click",e=>{if(e.target===habitModal)closeHabitModal()});
habitForm.addEventListener("submit",e=>{e.preventDefault();const id=habitEditingId.value.trim(),days=dowChks.filter(ch=>ch.checked).map(ch=>Number(ch.value));if(!days.length)return alert("Выбери хотя бы один активный день.");const h=normalizeHabit({id:id||uid(),name:habitName.value.trim(),emoji:habitEmoji.value.trim(),type:habitType.value,goal:habitGoal.value,days});if(!h.name)return alert("Укажи название.");const idx=state.habits.findIndex(x=>x.id===h.id);idx>=0?state.habits[idx]=h:state.habits.push(h);saveJSON(HABITS_KEY,state.habits);closeHabitModal();render()});
habitDeleteBtn.addEventListener("click",()=>{const id=habitEditingId.value.trim();if(!id)return;if(!confirm("Удалить привычку?"))return;state.habits=state.habits.filter(h=>h.id!==id);saveJSON(HABITS_KEY,state.habits);for(const d of Object.keys(state.log))state.log[d]&&id in state.log[d]&&delete state.log[d][id];saveJSON(LOG_KEY,state.log);closeHabitModal();render()});
tabs.forEach(b=>b.addEventListener("click",()=>{tabs.forEach(x=>x.classList.remove("active"));b.classList.add("active");state.tab=b.dataset.tab;render()}));
function daysLabel(days){const map={1:"Пн",2:"Вт",3:"Ср",4:"Чт",5:"Пт",6:"Сб",0:"Вс"};const s=days.slice().sort((a,b)=>(a===0?7:a)-(b===0?7:b));return s.map(d=>map[d]).join(" ")}
function completedToday(h){const t=todayISO(),v=getLogValue(t,h.id);return h.type==="count"?Number(v||0)>=h.goal:!!v}
function toggleCheck(id){const t=todayISO(),cur=!!getLogValue(t,id);setLogValue(t,id,!cur);renderToday()}
function incCount(id,delta){const t=todayISO(),h=state.habits.find(x=>x.id===id);if(!h)return;const cur=Number(getLogValue(t,id)||0);const next=Math.max(0,Math.min(h.goal,cur+delta));setLogValue(t,id,next);renderToday()}
function renderToday(){subtitleEl.textContent=`Сегодня • ${new Date().toLocaleDateString("ru-RU",{day:"2-digit",month:"long"})}`;viewEl.innerHTML="";if(!state.habits.length){viewEl.innerHTML=`<div class="card"><div class="cardTitle">Нет привычек</div><div class="cardMeta">Нажми “+ Привычка”, чтобы добавить.</div></div>`;return}state.habits.forEach(h=>{const active=isHabitActiveToday(h),done=completedToday(h),pill=done?`<span class="pill ok">Сделано</span>`:active?`<span class="pill warn">В процессе</span>`:`<span class="pill">Не сегодня</span>`;const title=`${h.emoji?h.emoji+" ":""}${h.name}`;const card=document.createElement("div");card.className="card"+(active?"":" itemDisabled");const meta=`<div>${h.type==="count"?`Цель: ${h.goal}`:"Чекбокс"}</div><div>Дни: ${daysLabel(h.days)}</div>`;let controls="";if(h.type==="check"){const checked=!!getLogValue(todayISO(),h.id);controls=`<div class="btnRow"><button class="btn primary" data-action="check" data-id="${h.id}" ${active?"":"disabled"}>${checked?"Снять":"Отметить"}</button><button class="btn" data-action="edit" data-id="${h.id}">Редактировать</button></div>`}else{const val=Number(getLogValue(todayISO(),h.id)||0);controls=`<div class="btnRow"><div class="counter"><button class="btn" data-action="dec" data-id="${h.id}" ${(active&&val>0)?"":"disabled"}>−</button><div class="counterVal">${val} / ${h.goal}</div><button class="btn primary" data-action="inc" data-id="${h.id}" ${(active&&val<h.goal)?"":"disabled"}>+</button></div><button class="btn" data-action="edit" data-id="${h.id}">Редактировать</button></div>`}card.innerHTML=`<div class="row1"><div><div class="cardTitle">${escapeHtml(title)}</div><div class="cardMeta">${meta}</div></div>${pill}</div>${controls}`;viewEl.appendChild(card)});viewEl.onclick=e=>{const b=e.target.closest("button[data-action]");if(!b)return;const id=b.dataset.id,act=b.dataset.action;if(act==="check")return toggleCheck(id);if(act==="inc")return incCount(id,1);if(act==="dec")return incCount(id,-1);if(act==="edit"){const h=state.habits.find(x=>x.id===id);if(h)openHabitModal(h)}}}
function renderHabits(){subtitleEl.textContent="Список привычек";viewEl.innerHTML="";if(!state.habits.length){viewEl.innerHTML=`<div class="card"><div class="cardTitle">Пока нет привычек</div><div class="cardMeta">Нажми “+ Привычка”, чтобы добавить.</div></div>`;return}state.habits.forEach(h=>{const title=`${h.emoji?h.emoji+" ":""}${h.name}`;const card=document.createElement("div");card.className="card";card.innerHTML=`<div class="row1"><div><div class="cardTitle">${escapeHtml(title)}</div><div class="cardMeta"><div>${h.type==="count"?`Счётчик • цель ${h.goal}`:"Чекбокс"}</div><div>Дни: ${daysLabel(h.days)}</div></div></div><button class="btn" data-action="edit" data-id="${h.id}">Редактировать</button></div>`;viewEl.appendChild(card)});viewEl.onclick=e=>{const b=e.target.closest("button[data-action='edit']");if(!b)return;const h=state.habits.find(x=>x.id===b.dataset.id);if(h)openHabitModal(h)}}
function lastNDates(n){const out=[],d=parseISO(todayISO());for(let i=0;i<n;i++){const cur=new Date(d);cur.setDate(cur.getDate()-i);out.push(isoFromDate(cur))}return out.reverse()}
function isCompletedOnDate(h,iso){const v=getLogValue(iso,h.id);return h.type==="count"?Number(v||0)>=h.goal:!!v}
function completionRate(h,n){const dates=lastNDates(n);let eligible=0,done=0;for(const iso of dates){const dow=parseISO(iso).getDay();if(!h.days.includes(dow))continue;eligible++;if(isCompletedOnDate(h,iso))done++}return{eligible,done,pct:eligible?Math.round(done*100/eligible):0}}
function streak(h){let count=0;const d=parseISO(todayISO());for(let i=0;i<3650;i++){const cur=new Date(d);cur.setDate(cur.getDate()-i);const iso=isoFromDate(cur);const dow=cur.getDay();if(!h.days.includes(dow))continue;if(isCompletedOnDate(h,iso))count++;else break}return count}
function renderStats(){subtitleEl.textContent="Статистика";viewEl.innerHTML="";if(!state.habits.length){viewEl.innerHTML=`<div class="card"><div class="cardTitle">Нет привычек</div></div>`;return}const active=state.habits.filter(isHabitActiveToday),done=active.filter(completedToday).length,pct=active.length?Math.round(done*100/active.length):0;const head=document.createElement("div");head.className="card";head.innerHTML=`<div class="cardTitle">Сегодня: ${done} / ${active.length} (${pct}%)</div><div class="cardMeta">Ниже — % за 7/30 дней и серия по каждой привычке.</div>`;viewEl.appendChild(head);state.habits.forEach(h=>{const r7=completionRate(h,7),r30=completionRate(h,30),st=streak(h),title=`${h.emoji?h.emoji+" ":""}${h.name}`;const card=document.createElement("div");card.className="card";card.innerHTML=`<div class="row1"><div><div class="cardTitle">${escapeHtml(title)}</div><div class="cardMeta"><div>Серия: <b>${st}</b></div><div>7 дней: ${r7.done}/${r7.eligible} (${r7.pct}%)</div><div>30 дней: ${r30.done}/${r30.eligible} (${r30.pct}%)</div></div></div><button class="btn" data-action="edit" data-id="${h.id}">Редактировать</button></div>`;viewEl.appendChild(card)});viewEl.onclick=e=>{const b=e.target.closest("button[data-action='edit']");if(!b)return;const h=state.habits.find(x=>x.id===b.dataset.id);if(h)openHabitModal(h)}}
function render(){state.tab==="today"?renderToday():state.tab==="habits"?renderHabits():renderStats()}
function openSettings(){settingsModal.classList.remove("hidden")}
function closeSettings(){settingsModal.classList.add("hidden")}
settingsBtn.addEventListener("click",openSettings);settingsCloseBtn.addEventListener("click",closeSettings);settingsDoneBtn.addEventListener("click",closeSettings);settingsModal.addEventListener("click",e=>{if(e.target===settingsModal)closeSettings()});
exportBtn.addEventListener("click",()=>{const data={habits:state.habits,log:state.log,settings:{pinHash:state.settings.pinHash?"SET":null}};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`habit-tracker-backup-${todayISO()}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)});
importFile.addEventListener("change",async()=>{const file=importFile.files?.[0];if(!file)return;try{const text=await file.text();const data=JSON.parse(text);if(!Array.isArray(data.habits)||typeof data.log!=="object")throw 0;state.habits=data.habits.map(normalizeHabit);state.log=data.log||{};saveJSON(HABITS_KEY,state.habits);saveJSON(LOG_KEY,state.log);alert("Импорт выполнен.");render()}catch{alert("Не удалось импортировать файл.")}finally{importFile.value=""}});
async function sha256(text){const enc=new TextEncoder().encode(text);const buf=await crypto.subtle.digest("SHA-256",enc);return[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function hasPin(){return!!state.settings.pinHash}
function showLock(){lockEl.classList.remove("hidden");pinInput.value="";pinError.classList.add("hidden");setTimeout(()=>pinInput.focus(),50)}
function hideLock(){lockEl.classList.add("hidden")}
async function tryUnlock(){const pin=pinInput.value.trim(),hash=await sha256(pin);hash===state.settings.pinHash?hideLock():pinError.classList.remove("hidden")}
pinUnlockBtn.addEventListener("click",tryUnlock);pinInput.addEventListener("keydown",e=>{if(e.key==="Enter")tryUnlock()});
function openPinModal(){pinModal.classList.remove("hidden");pinOld.value="";pinNew.value="";pinNew2.value="";if(hasPin()){pinModalTitle.textContent="Изменить PIN";pinHasExisting.classList.remove("hidden")}else{pinModalTitle.textContent="Включить PIN";pinHasExisting.classList.add("hidden")}}
function closePinModal(){pinModal.classList.add("hidden")}
pinActionBtn.addEventListener("click",openPinModal);pinCloseBtn.addEventListener("click",closePinModal);pinCancelBtn.addEventListener("click",closePinModal);pinModal.addEventListener("click",e=>{if(e.target===pinModal)closePinModal()});
pinDisableBtn.addEventListener("click",()=>{if(!hasPin())return closePinModal();if(!confirm("Отключить PIN?"))return;state.settings.pinHash=null;saveJSON(SETTINGS_KEY,state.settings);alert("PIN отключён.");closePinModal()});
pinForm.addEventListener("submit",async e=>{e.preventDefault();const n=pinNew.value.trim(),n2=pinNew2.value.trim();if(!/^\d{4,8}$/.test(n))return alert("PIN должен быть 4–8 цифр.");if(n!==n2)return alert("PIN не совпадает.");if(hasPin()){const o=pinOld.value.trim(),oh=await sha256(o);if(oh!==state.settings.pinHash)return alert("Текущий PIN неверный.")}state.settings.pinHash=await sha256(n);saveJSON(SETTINGS_KEY,state.settings);alert("PIN сохранён.");closePinModal();if(hasPin())showLock()});
function init(){registerSW();render();if(hasPin())showLock()}
init();
